export default {
    UPDATETITLE: 'UPDATETITLE',
    ADDQUESTION: 'ADDQUESTION',
    UPDATEQUESTION: 'UPDATEQUESTION',
    ADDOTHEROPTION: 'ADDOTHEROPTION',
    ADDOPTION: 'ADDOPTION',
    UPDATEOPTION: 'UPDATEOPTION'
}